window.D2D = window.D2D || {};

// Mirrors the Google Sheet 'PRODUCTS' tab schema (see js/config.js for the full column list).
// This seed array powers the Admin > Dashboard Collection screen until the Google Apps Script
// backend is connected — it is deliberately the same 15 dashboards shown on the public site.
D2D.PRODUCTS_SEED = [
    { product_id: "DB001", product_name: "HSE KPI Dashboard", category: "HSE", description: "Sistem pemantauan Keselamatan dan Kesihatan Pekerjaan dengan analitik insiden dan KPI keselamatan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/1e3a8a/ffffff?text=HSE+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.9, review_count: 45, demo_views: "1,200", purchase_count: 0, badge: "popular", status: 'active' },
    { product_id: "DB002", product_name: "OSH Dashboard", category: "OSH", description: "Papar KPI OSH, statistik insiden, audit keselamatan dan trend pematuhan dalam satu paparan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/2563eb/ffffff?text=OSH+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.8, review_count: 30, demo_views: "860", purchase_count: 0, badge: "featured", status: 'active' },
    { product_id: "DB003", product_name: "PAJSK Dashboard", category: "PAJSK", description: "Analisis pencapaian PAJSK pelajar mengikut domain, kelas dan tahun dengan carta interaktif.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/0ea5e9/ffffff?text=PAJSK+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.7, review_count: 18, demo_views: "540", purchase_count: 0, badge: "new", status: 'active' },
    { product_id: "DB004", product_name: "Akademik Dashboard", category: "Akademik", description: "Pantau prestasi akademik pelajar, purata gred, perbandingan kelas dan trend keputusan peperiksaan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/1d4ed8/ffffff?text=Akademik+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.9, review_count: 52, demo_views: "1,340", purchase_count: 0, badge: "bestseller", status: 'active' },
    { product_id: "DB005", product_name: "Kokurikulum Dashboard", category: "Kokurikulum", description: "Rekod penyertaan dan pencapaian kokurikulum pelajar mengikut unit, kelab dan persatuan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/3b82f6/ffffff?text=Kokurikulum+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.6, review_count: 14, demo_views: "410", purchase_count: 0, badge: "", status: 'active' },
    { product_id: "DB006", product_name: "Project Monitoring Dashboard", category: "Project", description: "Pantau status projek, bajet dan tugasan team dengan paparan Gantt chart mudah.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/1e40af/ffffff?text=Project+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.7, review_count: 34, demo_views: "980", purchase_count: 0, badge: "featured", status: 'active' },
    { product_id: "DB007", product_name: "Kos Projek Dashboard", category: "Project", description: "Analisis kos projek, perbelanjaan mengikut fasa dan perbandingan bajet vs actual.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/1e3a8a/ffffff?text=Kos+Projek+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.8, review_count: 22, demo_views: "610", purchase_count: 0, badge: "", status: 'active' },
    { product_id: "DB008", product_name: "Operasi Projek Dashboard", category: "Project", description: "Pantau status kerja, milestone dan prestasi operasi projek secara real-time.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/2563eb/ffffff?text=Operasi+Projek+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.7, review_count: 16, demo_views: "480", purchase_count: 0, badge: "", status: 'active' },
    { product_id: "DB009", product_name: "Finance Dashboard", category: "Finance", description: "Laporan kewangan, aliran tunai dan analisis perbelanjaan syarikat harian.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/0f172a/38bdf8?text=Finance+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.9, review_count: 56, demo_views: "1,450", purchase_count: 0, badge: "popular", status: 'active' },
    { product_id: "DB010", product_name: "Result Exam Dashboard", category: "Akademik", description: "Analisis keputusan peperiksaan mengikut subjek, kelas dan gred dengan perbandingan tahun ke tahun.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/1d4ed8/ffffff?text=Result+Exam+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.8, review_count: 27, demo_views: "700", purchase_count: 0, badge: "new", status: 'active' },
    { product_id: "DB011", product_name: "HR Management Dashboard", category: "HR", description: "Urus rekod pekerja, kehadiran, dan KPI kakitangan dalam satu sistem bersepadu.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/2b4162/ffffff?text=HR+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.8, review_count: 82, demo_views: "2,500", purchase_count: 0, badge: "bestseller", status: 'active' },
    { product_id: "DB012", product_name: "Inventory Dashboard", category: "Inventory", description: "Urus stok barang masuk dan keluar dengan notifikasi stok rendah (low stock alert).", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/662e9b/ffffff?text=Inventory+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 5.0, review_count: 12, demo_views: "430", purchase_count: 0, badge: "new", status: 'active' },
    { product_id: "DB013", product_name: "Sales Performance Dashboard", category: "Operations", description: "Track sales harian, target bulanan, dan prestasi agen jualan syarikat anda.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/ea3546/ffffff?text=Sales+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.6, review_count: 28, demo_views: "890", purchase_count: 0, badge: "", status: 'active' },
    { product_id: "DB014", product_name: "Training Dashboard", category: "Education", description: "Rekod latihan staf, jam kursus, sijil tamat dan analisis bajet latihan tahunan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/0392cf/ffffff?text=Training+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.8, review_count: 19, demo_views: "600", purchase_count: 0, badge: "", status: 'active' },
    { product_id: "DB015", product_name: "Asset Management Dashboard", category: "Operations", description: "Sistem inventori aset syarikat, susut nilai, lokasi aset dan rekod penyelenggaraan.", price_self_setup: 90, price_full_setup: 180, demo_url: "", powerbi_available: true, thumbnail: "https://via.placeholder.com/400x250/7bc043/ffffff?text=Asset+Dashboard", preview_image: '', features: 'Responsive dashboard, KPI cards, Interactive charts, Filter / slicer, Search functionality, Data table, CRUD compatible, Mobile friendly', technology: 'HTML5, CSS3, JavaScript, Microsoft Excel, Microsoft Power BI, Google Apps Script, Google Sheet', rating: 4.9, review_count: 41, demo_views: "1,150", purchase_count: 0, badge: "popular", status: 'active' }
];
